# Generated by Django 2.1.8 on 2019-09-10 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190910_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexgoodsbanner',
            name='sku',
        ),
    ]
